import { RaceData } from "./race.interface";

export const raceDataFiller: RaceData[] = [
  {
    id: "human",
    board_spectrum:
      "With their penchant for migration and conquest, humans are more physically diverse than other common races. There is no typical human. An individual can stand from 5 feet to a little over 6 feet tall and weigh from 125 to 250 pounds. Human skin shades range from nearly black to very pale, and hair colors from black to blond (curly, kinky, or straight); males might sport facial hair that is sparse or thick. A lot of humans have a dash of nonhuman blood, revealing hints of elf, orc, or other lineages. Humans reach adulthood in their late teens and rarely live even a single century.",
    variety: {
      text: "Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled. When they settle, they build cities to last for the ages, and great kingdoms that can persist for long centuries. They live fully in the present and plan for the future, striving to leave a lasting legacy. Individually and as a group, humans are adaptable opportunists, staying alert to changing political and social dynamics.",
      quote:
        "Just as readily as they mix with each other, humans mingle with members of other races. They get along with almost everyone, though they might not be close to many. Humans serve as ambassadors, diplomats, magistrates, merchants, and functionaries of all kinds.\nDwarves: “They’re stout folk, stalwart friends, and true to their word. Their greed for gold is their downfall, though.”\nElves: “It’s best not to wander into elven woods. They don’t like intruders, and you’ll as likely be bewitched as peppered with arrows. Still, if an elf can get past that damned racial pride and actually treat you like an equal, you can learn a lot from them.”\nHalflings: “It’s hard to beat a meal in a halfling home, as long as you don’t crack your head on the ceiling—good food and good stories in front of a nice, warm fire. If halflings had a shred of ambition, they might really amount to something.”",
    },
    institutions:
      "Where a single elf or dwarf might guard a special location or secret, humans found sacred orders and institutions for such purposes. Temples, governments, libraries, and codes of law fix their traditions in history. Humans dream of immortality, achieving it by ensuring they will be remembered. Human societies are generally inclusive, welcoming large numbers of nonhumans compared to the proportion of humans in nonhuman lands.",
    ambitions:
      "Humans seeking adventure are the most daring and ambitious members of a daring and ambitious race. They aim to earn glory by amassing power, wealth, and fame. Humans champion causes rather than territories or groups.",
    ethnic:
      "Having so much more variety than other cultures, humans as a whole have no typical names. Some human parents give their children names from other languages, such as Dwarvish or Elvish (pronounced more or less correctly), but most parents give names that are linked to their region’s culture or to the naming traditions of their ancestors. The material culture and physical characteristics of humans can change wildly from region to region. In the Forgotten Realms, for example, the clothing, architecture, cuisine, music, and literature are different in the northwestern lands of the Silver Marches than in distant Turmish or Impiltur to the east—and even more distinctive in far-off Kara-Tur. Human physical characteristics, though, vary according to the ancient migrations of the earliest humans, so that the humans of the Silver Marches have every possible variation of coloration and features. In the Forgotten Realms, nine human ethnic groups are widely recognized, though over a dozen others are found in more localized areas of Faerûn. These groups, and the typical names of their members, can be used as inspiration no matter which world your human is in.",
    ethnic_groups: [
      {
        name: "Calishite",
        description:
          "Shorter and slighter in build than most other humans, Calishites have dusky brown skin, hair, and eyes. They’re found primarily in southwest Faerûn.",
        names: {
          male: [
            "Aseir",
            "Bardeid",
            "Haseid",
            "Khemed",
            "Mehmen",
            "Sudeiman",
            "Zasheir",
          ],
          female: [
            "Atala",
            "Ceidil",
            "Hama",
            "Jasmal",
            "Meilil",
            "Seipora",
            "Yasheira",
            "Zasheida",
          ],
          surnames: [
            "Basha",
            "Dumein",
            "Jassan",
            "Khalid",
            "Mostana",
            "Pashar",
            "Rein",
          ],
        },
      },
      {
        name: "Chondathan",
        description:
          "Slender, tawny-skinned folk with brown hair ranging from almost blond to almost black. They dominate the central lands of Faerûn, around the Inner Sea.",
        names: {
          male: [
            "Darvin",
            "Dorn",
            "Evendur",
            "Gorstag",
            "Grim",
            "Helm",
            "Malark",
            "Morn",
            "Randal",
            "Stedd",
          ],
          female: [
            "Arveene",
            "Esvele",
            "Jhessail",
            "Kerri",
            "Lureene",
            "Miri",
            "Rowan",
            "Shandri",
            "Tessele",
          ],
          surnames: [
            "Amblecrown",
            "Buckman",
            "Dundragon",
            "Evenwood",
            "Greycastle",
            "Tallstag",
          ],
        },
      },
      {
        name: "Damaran",
        description:
          "Moderate height and build, with skin hues ranging from tawny to fair. Primarily found in the northwest of Faerûn.",
        names: {
          male: [
            "Bor",
            "Fodel",
            "Glar",
            "Grigor",
            "Igan",
            "Ivor",
            "Kosef",
            "Mival",
            "Orel",
            "Pavel",
            "Sergor",
          ],
          female: [
            "Alethra",
            "Kara",
            "Katernin",
            "Mara",
            "Natali",
            "Olma",
            "Tana",
            "Zora",
          ],
          surnames: [
            "Bersk",
            "Chernin",
            "Dotsk",
            "Kulenov",
            "Marsk",
            "Nemetsk",
            "Shemov",
            "Starag",
          ],
        },
      },
      {
        name: "Illuskan",
        description:
          "Tall, fair-skinned folk with blue or steely gray eyes, prevalent in the extreme northwest. Hair colors range from black to blond.",
        names: {
          male: [
            "Ander",
            "Blath",
            "Bran",
            "Frath",
            "Geth",
            "Lander",
            "Luth",
            "Malcer",
            "Stor",
            "Taman",
            "Urth",
          ],
          female: [
            "Amafrey",
            "Betha",
            "Cefrey",
            "Kethra",
            "Mara",
            "Olga",
            "Silifrey",
            "Westra",
          ],
          surnames: [
            "Brightwood",
            "Helder",
            "Hornraven",
            "Lackman",
            "Stormwind",
            "Windrivver",
          ],
        },
      },
      {
        name: "Mulan",
        description:
          "Tall, slim, and amber-skinned, found in the eastern and southeastern shores of the Inner Sea. Hair ranges from black to dark brown.",
        names: {
          male: [
            "Aoth",
            "Bareris",
            "Ehput-Ki",
            "Kethoth",
            "Mumed",
            "Ramas",
            "So-Kehur",
            "Thazar-De",
            "Urhur",
          ],
          female: [
            "Arizima",
            "Chathi",
            "Nephis",
            "Nulara",
            "Murithi",
            "Sefris",
            "Thola",
            "Umara",
            "Zolis",
          ],
          surnames: [
            "Ankhalab",
            "Anskuld",
            "Fezim",
            "Hahpet",
            "Nathandem",
            "Sepret",
            "Uuthrakt",
          ],
        },
      },
      {
        name: "Rashemi",
        description:
          "Short, stout, and muscular with dusky skin, dark eyes, and thick black hair. Commonly found east of the Inner Sea.",
        names: {
          male: [
            "Borivik",
            "Faurgar",
            "Jandar",
            "Kanithar",
            "Madislak",
            "Ralmevik",
            "Shaumar",
            "Vladislak",
          ],
          female: [
            "Fyevarra",
            "Hulmarra",
            "Immith",
            "Imzel",
            "Navarra",
            "Shevarra",
            "Tammith",
            "Yuldra",
          ],
          surnames: [
            "Chergoba",
            "Dyernina",
            "Iltazyara",
            "Murnyethara",
            "Stayanoga",
            "Ulmokina",
          ],
        },
      },
      {
        name: "Shou",
        description:
          "Yellowish-bronze in hue, with black hair and dark eyes. Native to Kara-Tur, far to the east of Faerûn.",
        names: {
          male: [
            "An",
            "Chen",
            "Chi",
            "Fai",
            "Jiang",
            "Jun",
            "Lian",
            "Long",
            "Meng",
            "On",
            "Shan",
            "Shui",
            "Wen",
          ],
          female: ["Bai", "Chao", "Jia", "Lei", "Mei", "Qiao", "Shui", "Tai"],
          surnames: [
            "Chien",
            "Huang",
            "Kao",
            "Kung",
            "Lao",
            "Ling",
            "Mei",
            "Pin",
            "Shin",
            "Sum",
            "Tan",
            "Wan",
          ],
        },
      },
      {
        name: "Tethyrian",
        description:
          "Medium build and height with dusky skin that grows fairer the farther north they dwell. Hair and eye color varies widely.",
        names: {
          male: ["Tethyrians primarily use Chondathan names."],
          female: ["Tethyrians primarily use Chondathan names."],
          surnames: [],
        },
      },
      {
        name: "Turami",
        description:
          "Tall and muscular with dark mahogany skin, curly black hair, and dark eyes. Native to the southern shore of the Inner Sea.",
        names: {
          male: [
            "Anton",
            "Diero",
            "Marcon",
            "Pieron",
            "Rimardo",
            "Romero",
            "Salazar",
            "Umbero",
          ],
          female: [
            "Balama",
            "Dona",
            "Faila",
            "Jalana",
            "Luisa",
            "Marta",
            "Quara",
            "Selise",
            "Vonda",
          ],
          surnames: [
            "Agosto",
            "Astorio",
            "Calabra",
            "Domine",
            "Falone",
            "Marivaldi",
            "Pisacar",
            "Ramondo",
          ],
        },
      },
    ],
  },

  {
    id: "half-elf",
    board_spectrum:
      "ELF their penchant for migration and conquest, humans are more physically diverse than other common races. There is no typical human. An individual can stand from 5 feet to a little over 6 feet tall and weigh from 125 to 250 pounds. Human skin shades range from nearly black to very pale, and hair colors from black to blond (curly, kinky, or straight); males might sport facial hair that is sparse or thick. A lot of humans have a dash of nonhuman blood, revealing hints of elf, orc, or other lineages. Humans reach adulthood in their late teens and rarely live even a single century.",
    variety: {
      text: "Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled. When they settle, they build cities to last for the ages, and great kingdoms that can persist for long centuries. They live fully in the present and plan for the future, striving to leave a lasting legacy. Individually and as a group, humans are adaptable opportunists, staying alert to changing political and social dynamics.",
      quote:
        "Just as readily as they mix with each other, humans mingle with members of other races. They get along with almost everyone, though they might not be close to many. Humans serve as ambassadors, diplomats, magistrates, merchants, and functionaries of all kinds.\nDwarves: “They’re stout folk, stalwart friends, and true to their word. Their greed for gold is their downfall, though.”\nElves: “It’s best not to wander into elven woods. They don’t like intruders, and you’ll as likely be bewitched as peppered with arrows. Still, if an elf can get past that damned racial pride and actually treat you like an equal, you can learn a lot from them.”\nHalflings: “It’s hard to beat a meal in a halfling home, as long as you don’t crack your head on the ceiling—good food and good stories in front of a nice, warm fire. If halflings had a shred of ambition, they might really amount to something.”",
    },
    institutions:
      "Where a single elf or dwarf might guard a special location or secret, humans found sacred orders and institutions for such purposes. Temples, governments, libraries, and codes of law fix their traditions in history. Humans dream of immortality, achieving it by ensuring they will be remembered. Human societies are generally inclusive, welcoming large numbers of nonhumans compared to the proportion of humans in nonhuman lands.",
    ambitions:
      "Humans seeking adventure are the most daring and ambitious members of a daring and ambitious race. They aim to earn glory by amassing power, wealth, and fame. Humans champion causes rather than territories or groups.",
    ethnic:
      "Having so much more variety than other cultures, humans as a whole have no typical names. Some human parents give their children names from other languages, such as Dwarvish or Elvish (pronounced more or less correctly), but most parents give names that are linked to their region’s culture or to the naming traditions of their ancestors. The material culture and physical characteristics of humans can change wildly from region to region. In the Forgotten Realms, for example, the clothing, architecture, cuisine, music, and literature are different in the northwestern lands of the Silver Marches than in distant Turmish or Impiltur to the east—and even more distinctive in far-off Kara-Tur. Human physical characteristics, though, vary according to the ancient migrations of the earliest humans, so that the humans of the Silver Marches have every possible variation of coloration and features. In the Forgotten Realms, nine human ethnic groups are widely recognized, though over a dozen others are found in more localized areas of Faerûn. These groups, and the typical names of their members, can be used as inspiration no matter which world your human is in.",
    ethnic_groups: [
      {
        name: "Calishite",
        description:
          "Shorter and slighter in build than most other humans, Calishites have dusky brown skin, hair, and eyes. They’re found primarily in southwest Faerûn.",
        names: {
          male: [
            "Aseir",
            "Bardeid",
            "Haseid",
            "Khemed",
            "Mehmen",
            "Sudeiman",
            "Zasheir",
          ],
          female: [
            "Atala",
            "Ceidil",
            "Hama",
            "Jasmal",
            "Meilil",
            "Seipora",
            "Yasheira",
            "Zasheida",
          ],
          surnames: [
            "Basha",
            "Dumein",
            "Jassan",
            "Khalid",
            "Mostana",
            "Pashar",
            "Rein",
          ],
        },
      },
      {
        name: "Chondathan",
        description:
          "Slender, tawny-skinned folk with brown hair ranging from almost blond to almost black. They dominate the central lands of Faerûn, around the Inner Sea.",
        names: {
          male: [
            "Darvin",
            "Dorn",
            "Evendur",
            "Gorstag",
            "Grim",
            "Helm",
            "Malark",
            "Morn",
            "Randal",
            "Stedd",
          ],
          female: [
            "Arveene",
            "Esvele",
            "Jhessail",
            "Kerri",
            "Lureene",
            "Miri",
            "Rowan",
            "Shandri",
            "Tessele",
          ],
          surnames: [
            "Amblecrown",
            "Buckman",
            "Dundragon",
            "Evenwood",
            "Greycastle",
            "Tallstag",
          ],
        },
      },
      {
        name: "Damaran",
        description:
          "Moderate height and build, with skin hues ranging from tawny to fair. Primarily found in the northwest of Faerûn.",
        names: {
          male: [
            "Bor",
            "Fodel",
            "Glar",
            "Grigor",
            "Igan",
            "Ivor",
            "Kosef",
            "Mival",
            "Orel",
            "Pavel",
            "Sergor",
          ],
          female: [
            "Alethra",
            "Kara",
            "Katernin",
            "Mara",
            "Natali",
            "Olma",
            "Tana",
            "Zora",
          ],
          surnames: [
            "Bersk",
            "Chernin",
            "Dotsk",
            "Kulenov",
            "Marsk",
            "Nemetsk",
            "Shemov",
            "Starag",
          ],
        },
      },
      {
        name: "Illuskan",
        description:
          "Tall, fair-skinned folk with blue or steely gray eyes, prevalent in the extreme northwest. Hair colors range from black to blond.",
        names: {
          male: [
            "Ander",
            "Blath",
            "Bran",
            "Frath",
            "Geth",
            "Lander",
            "Luth",
            "Malcer",
            "Stor",
            "Taman",
            "Urth",
          ],
          female: [
            "Amafrey",
            "Betha",
            "Cefrey",
            "Kethra",
            "Mara",
            "Olga",
            "Silifrey",
            "Westra",
          ],
          surnames: [
            "Brightwood",
            "Helder",
            "Hornraven",
            "Lackman",
            "Stormwind",
            "Windrivver",
          ],
        },
      },
      {
        name: "Mulan",
        description:
          "Tall, slim, and amber-skinned, found in the eastern and southeastern shores of the Inner Sea. Hair ranges from black to dark brown.",
        names: {
          male: [
            "Aoth",
            "Bareris",
            "Ehput-Ki",
            "Kethoth",
            "Mumed",
            "Ramas",
            "So-Kehur",
            "Thazar-De",
            "Urhur",
          ],
          female: [
            "Arizima",
            "Chathi",
            "Nephis",
            "Nulara",
            "Murithi",
            "Sefris",
            "Thola",
            "Umara",
            "Zolis",
          ],
          surnames: [
            "Ankhalab",
            "Anskuld",
            "Fezim",
            "Hahpet",
            "Nathandem",
            "Sepret",
            "Uuthrakt",
          ],
        },
      },
      {
        name: "Rashemi",
        description:
          "Short, stout, and muscular with dusky skin, dark eyes, and thick black hair. Commonly found east of the Inner Sea.",
        names: {
          male: [
            "Borivik",
            "Faurgar",
            "Jandar",
            "Kanithar",
            "Madislak",
            "Ralmevik",
            "Shaumar",
            "Vladislak",
          ],
          female: [
            "Fyevarra",
            "Hulmarra",
            "Immith",
            "Imzel",
            "Navarra",
            "Shevarra",
            "Tammith",
            "Yuldra",
          ],
          surnames: [
            "Chergoba",
            "Dyernina",
            "Iltazyara",
            "Murnyethara",
            "Stayanoga",
            "Ulmokina",
          ],
        },
      },
      {
        name: "Shou",
        description:
          "Yellowish-bronze in hue, with black hair and dark eyes. Native to Kara-Tur, far to the east of Faerûn.",
        names: {
          male: [
            "An",
            "Chen",
            "Chi",
            "Fai",
            "Jiang",
            "Jun",
            "Lian",
            "Long",
            "Meng",
            "On",
            "Shan",
            "Shui",
            "Wen",
          ],
          female: ["Bai", "Chao", "Jia", "Lei", "Mei", "Qiao", "Shui", "Tai"],
          surnames: [
            "Chien",
            "Huang",
            "Kao",
            "Kung",
            "Lao",
            "Ling",
            "Mei",
            "Pin",
            "Shin",
            "Sum",
            "Tan",
            "Wan",
          ],
        },
      },
      {
        name: "Tethyrian",
        description:
          "Medium build and height with dusky skin that grows fairer the farther north they dwell. Hair and eye color varies widely.",
        names: {
          male: ["Tethyrians primarily use Chondathan names."],
          female: ["Tethyrians primarily use Chondathan names."],
          surnames: [],
        },
      },
      {
        name: "Turami",
        description:
          "Tall and muscular with dark mahogany skin, curly black hair, and dark eyes. Native to the southern shore of the Inner Sea.",
        names: {
          male: [
            "Anton",
            "Diero",
            "Marcon",
            "Pieron",
            "Rimardo",
            "Romero",
            "Salazar",
            "Umbero",
          ],
          female: [
            "Balama",
            "Dona",
            "Faila",
            "Jalana",
            "Luisa",
            "Marta",
            "Quara",
            "Selise",
            "Vonda",
          ],
          surnames: [
            "Agosto",
            "Astorio",
            "Calabra",
            "Domine",
            "Falone",
            "Marivaldi",
            "Pisacar",
            "Ramondo",
          ],
        },
      },
    ],
  },
];
